/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mstr_product;

import mstr_product.*;
import Class.DBO;
import Class.mstr_product;
import java.awt.Dimension;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Lisda
 */
public class _List extends javax.swing.JInternalFrame {
    
    private boolean appeand;
    private DefaultTableModel _tempttrs_mstr_product;
    Connection _Cnn;
    String _User;

    /**
     * Creates new form _List
     */
    public _List() {
        initComponents();
        
        String[] kolomtbl = {"`PRD ID`", " `NAMA`", " `SATUAN`", "HARGA"};
        _tempttrs_mstr_product = new DefaultTableModel(null, kolomtbl){
            Class[] types = new Class[]{
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class
            };
            
            public Class getColumnClass(int columnIndex){
                return types[columnIndex];
            }
            
            public boolean isCellEditable(int row, int col){
                int kol = _tempttrs_mstr_product.getColumnCount();
                return (col < kol) ? false : true;
            }
            
        };
        tbl_mstr_product.setModel(_tempttrs_mstr_product);
        loadData();
    }
    
    public void hapusRowData(){
        int row = _tempttrs_mstr_product.getColumnCount();
        // for (int i = 0; i < row; i++);
        // {
        //      _tempttrs_mstr_customer.removeRow(0);
        // }
        while (_tempttrs_mstr_product.getRowCount() > 0){
            _tempttrs_mstr_product.setRowCount(0); //removeRow(0);
        }
    }

    private void loadData(){
        String _sql = "";
        DBO vcon = new DBO();
        vcon.makeConnect();
        hapusRowData();
        try {
            _Cnn = vcon.vkoneksi;
            if (txt_cari_produk.getText().equals("")){
                _sql = ""
                        + "SELECT `prd_id`, `nama`, `satuan`, `harga` FROM `mstr_product`";
            }else{
                _sql = ""
                        +"SELECT * FROM mstr_product "
                        +"WHERE prd_id LIKE '%" + txt_cari_produk.getText() + "%' OR"
                        +"`nama` LIKE '% " + txt_cari_produk.getText() + "%' OR"
                        +"`satuan` LIKE '% " + txt_cari_produk.getText() + "%' OR"
                        +"`harga` LIKE '% " + txt_cari_produk.getText() + "%'";
            }
            System.out.println(_sql);
            Statement st = _Cnn.createStatement();
            ResultSet rst = st.executeQuery(_sql);
            while (rst.next()){
                String prd_id = rst.getString(1);
                String nama = rst.getString(2);
                String satuan = rst.getString(3);
                String harga = rst.getString(4);

                Object[] data = {prd_id, nama, satuan, harga};
                _tempttrs_mstr_product.addRow(data);
            }
            tbl_mstr_product.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbl_mstr_product.getColumnModel().getColumn(1).setPreferredWidth(210);
            tbl_mstr_product.getColumnModel().getColumn(2).setPreferredWidth(100);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }
    }
    
    ActionListener actionlist;
    private javax.swing.Timer timer = new javax.swing.Timer(10, actionlist);
    
    private void refresh(){
        try {
            loadData();
            ActionListener acl = new ActionListener(){
                public void actionPerformed(ActionEvent ae){
                    timer.stop();
                }
            };
            timer = new javax.swing.Timer(100, acl);
            timer.start();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTitledPanel2 = new org.jdesktop.swingx.JXTitledPanel();
        jLabel1 = new javax.swing.JLabel();
        Bubah = new javax.swing.JButton();
        BTambah = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        Brefresh = new javax.swing.JButton();
        Bkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mstr_product = new javax.swing.JTable();
        txt_cari_produk = new javax.swing.JTextField();

        jXTitledPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jXTitledPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jXTitledPanel2.setTitle(" _List Data Product");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Pencarian");

        Bubah.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Bubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-file-icon.png"))); // NOI18N
        Bubah.setText("Ubah");
        Bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BubahActionPerformed(evt);
            }
        });

        BTambah.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Folder-Add-icon.png"))); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        BHapus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Windows-Close-Program-icon (1).png"))); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        Brefresh.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Brefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Window-Refresh-icon.png"))); // NOI18N
        Brefresh.setText("Refresh");
        Brefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrefreshActionPerformed(evt);
            }
        });

        Bkeluar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Bkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout-icon.png"))); // NOI18N
        Bkeluar.setText("Keluar");
        Bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkeluarActionPerformed(evt);
            }
        });

        tbl_mstr_product.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbl_mstr_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_mstr_product);

        txt_cari_produk.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_cari_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_produkActionPerformed(evt);
            }
        });
        txt_cari_produk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cari_produkKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cari_produkKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jXTitledPanel2Layout = new javax.swing.GroupLayout(jXTitledPanel2.getContentContainer());
        jXTitledPanel2.getContentContainer().setLayout(jXTitledPanel2Layout);
        jXTitledPanel2Layout.setHorizontalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bkeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Brefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jXTitledPanel2Layout.setVerticalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_cari_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Bubah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTambah)
                        .addGap(18, 18, 18)
                        .addComponent(BHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Brefresh)
                        .addGap(18, 18, 18)
                        .addComponent(Bkeluar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jXTitledPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BubahActionPerformed
         try {
            String kode = tbl_mstr_product.getValueAt(tbl_mstr_product.getSelectedRow(), 0).toString();
            _Entry f = new _Entry("", kode, "Edit");
            Dimension parentSize = this.getSize();
            f.setLocation((parentSize.width) / 2, (parentSize.height) / 2);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            f.BKeluar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    loadData();                    
                }
            });
            f.bSimpan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    refresh();                    
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR " + e);
        }
    }//GEN-LAST:event_BubahActionPerformed

    private void BkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkeluarActionPerformed
       this.dispose();
    }//GEN-LAST:event_BkeluarActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        try {
            _Entry f = new _Entry("", "", "Add");
            Dimension parentSize = this.getSize();
            f.setLocation((parentSize.width) / 2, (parentSize.height) / 2);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            f.BKeluar.addActionListener(new java.awt.event.ActionListener(){
                public void actionPerformed(java.awt.event.ActionEvent evt){
                    refresh();
                }
            });
            f.bSimpan.addActionListener(new java.awt.event.ActionListener(){
                public void actionPerformed(java.awt.event.ActionEvent evt){
                    loadData();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_BTambahActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        String kode = tbl_mstr_product.getValueAt(tbl_mstr_product.getSelectedRow(), 0).toString();
        int pilih = JOptionPane.showConfirmDialog(this, "Hapus data product : " + kode, "KONFIRMASI", JOptionPane.YES_NO_OPTION);
        if (pilih == JOptionPane.YES_OPTION){
            mstr_product x = new mstr_product();
            x.hapusdata(kode);
            refresh();
            loadData();
        }
    }//GEN-LAST:event_BHapusActionPerformed

    private void txt_cari_produkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_produkKeyPressed
        try {
            refresh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_txt_cari_produkKeyPressed

    private void txt_cari_produkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_produkKeyReleased
       try {
            refresh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_txt_cari_produkKeyReleased

    private void txt_cari_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_produkActionPerformed

    }//GEN-LAST:event_txt_cari_produkActionPerformed

    private void BrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrefreshActionPerformed
       try {
            refresh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_BrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BTambah;
    private javax.swing.JButton Bkeluar;
    private javax.swing.JButton Brefresh;
    private javax.swing.JButton Bubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel2;
    private javax.swing.JTable tbl_mstr_product;
    private javax.swing.JTextField txt_cari_produk;
    // End of variables declaration//GEN-END:variables
}
