package penjualan;


import Class.DBO;
import java.awt.*;
import javax.swing.*;
import report.FrmLaporan;
/**
 *
 * @author Lisda
 */
public class frmMenuUtama extends javax.swing.JFrame {
    private boolean append;
    Dimension parentSize = this.getSize();
    /**
     * Creates new form frmMenuUtama
     */
    public frmMenuUtama() {
        initComponents();
        settingkoneksi();
        setSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
    }
    
    private void settingkoneksi(){
        DBO setting = new DBO();
        setting.makeConnect();
        if (setting.isConnected() == true){
            JOptionPane.showMessageDialog(null, "Terhubung dengan Database");
        }else{
            JOptionPane.showMessageDialog(null, "Koneksi database gagal");
        }
    }
    
    private void linkuser(){
        mstr_user._List fus = new mstr_user._List();
        fus = new mstr_user._List();
        jDesktopPane1.add(fus);
        parentSize = this.getSize();
        Dimension childsize = fus.getSize();
        fus.setLocation((parentSize.width - childsize.width) / 2, (parentSize.height - childsize.height) / 2);
        fus.setVisible(true);
    }
    
    private void linkcust(){
        mstr_customer._List fu = new mstr_customer._List();
        fu = new mstr_customer._List();
        jDesktopPane1.add(fu);
        parentSize = this.getSize();
        Dimension childsize = fu.getSize();
        fu.setLocation((parentSize.width - childsize.width) / 2, (parentSize.height - childsize.height) / 2);
        fu.setVisible(true);
    }

    private void linkproduk(){
        mstr_product._List fp = new mstr_product._List();
        fp = new mstr_product._List();
        jDesktopPane1.add(fp);
        parentSize = this.getSize();
        Dimension childsize = fp.getSize();
        fp.setLocation((parentSize.width - childsize.width) / 2, (parentSize.height - childsize.height) / 2);
        fp.setVisible(true);
    }
    
    private void linkpenjualan(){
        ttrs_penjualan._List ftp = new ttrs_penjualan._List();
        ftp = new ttrs_penjualan._List();
        jDesktopPane1.add(ftp);
        parentSize = this.getSize();
        Dimension childsize = ftp.getSize();
        ftp.setLocation((parentSize.width - childsize.width) / 2, (parentSize.height - childsize.height) / 2);
        ftp.setVisible(true);
    }
    
    private void LFrmCustomer(){
        FrmLaporan l = new FrmLaporan();
        jDesktopPane1.add(l);
        parentSize = this.getSize();
        Dimension childsize = l.getSize();
        l.setLocation((parentSize.width - childsize.width) / 2, (parentSize.height - childsize.height) / 2);
        l.setVisible(true);
        l.btampil.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                l.btampil.setText("Cetak Data Customer");
            }
        });
    }
    
    private void LFrmUser(){
        FrmLaporan l = new FrmLaporan();
        jDesktopPane1.add(l);
        parentSize = this.getSize();
        Dimension childsize = l.getSize();
        l.setLocation((parentSize.width - childsize.width) / 2, (parentSize.height - childsize.height) / 2);
        l.setVisible(true);
        l.btampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt){
                l.btampil.setText("Cetak Data User");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        kontrol = new javax.swing.JMenu();
        SU_Login = new javax.swing.JMenuItem();
        SU_Logout = new javax.swing.JMenuItem();
        SU_Keluar = new javax.swing.JMenuItem();
        master = new javax.swing.JMenu();
        m_user = new javax.swing.JMenuItem();
        m_product = new javax.swing.JMenuItem();
        m_customer = new javax.swing.JMenuItem();
        ttrs = new javax.swing.JMenu();
        ttrs_penjualan = new javax.swing.JMenuItem();
        lap = new javax.swing.JMenu();
        l_user = new javax.swing.JMenuItem();
        l_cust = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        kontrol.setText("Switch");

        SU_Login.setText("Login");
        SU_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SU_LoginActionPerformed(evt);
            }
        });
        kontrol.add(SU_Login);

        SU_Logout.setText("Logout");
        SU_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SU_LogoutActionPerformed(evt);
            }
        });
        kontrol.add(SU_Logout);

        SU_Keluar.setText("Keluar");
        SU_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SU_KeluarActionPerformed(evt);
            }
        });
        kontrol.add(SU_Keluar);

        jMenuBar1.add(kontrol);

        master.setText("Master");

        m_user.setText("User");
        m_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_userActionPerformed(evt);
            }
        });
        master.add(m_user);

        m_product.setText("Product");
        m_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_productActionPerformed(evt);
            }
        });
        master.add(m_product);

        m_customer.setText("Customer");
        m_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_customerActionPerformed(evt);
            }
        });
        master.add(m_customer);

        jMenuBar1.add(master);

        ttrs.setText("Transaksi");

        ttrs_penjualan.setText("Transaksi Penjualan");
        ttrs_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttrs_penjualanActionPerformed(evt);
            }
        });
        ttrs.add(ttrs_penjualan);

        jMenuBar1.add(ttrs);

        lap.setText("Laporan");

        l_user.setText("Laporan User");
        l_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_userActionPerformed(evt);
            }
        });
        lap.add(l_user);

        l_cust.setText("Laporan Customer");
        l_cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_custActionPerformed(evt);
            }
        });
        lap.add(l_cust);

        jMenuBar1.add(lap);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SU_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SU_LoginActionPerformed
        FrmLogin fl = new FrmLogin();
        parentSize = this.getSize();
        Dimension childsize = fl.getSize();
        fl.setLocation((parentSize.width - childsize.width) / 2, (parentSize.height - childsize.height) / 2);
        fl.setVisible(true);
    }//GEN-LAST:event_SU_LoginActionPerformed

    private void SU_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SU_LogoutActionPerformed
        append = false;
        this.setVisible(append);
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_SU_LogoutActionPerformed

    private void m_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_userActionPerformed
        linkuser();
    }//GEN-LAST:event_m_userActionPerformed

    private void m_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_productActionPerformed
         linkproduk();
    }//GEN-LAST:event_m_productActionPerformed

    private void l_custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_custActionPerformed
        LFrmCustomer();
    }//GEN-LAST:event_l_custActionPerformed

    private void SU_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SU_KeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SU_KeluarActionPerformed

    private void m_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_customerActionPerformed
        linkcust();
    }//GEN-LAST:event_m_customerActionPerformed

    private void ttrs_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttrs_penjualanActionPerformed
        linkpenjualan();
    }//GEN-LAST:event_ttrs_penjualanActionPerformed

    private void l_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_userActionPerformed
        LFrmUser();
    }//GEN-LAST:event_l_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SU_Keluar;
    private javax.swing.JMenuItem SU_Login;
    private javax.swing.JMenuItem SU_Logout;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu kontrol;
    private javax.swing.JMenuItem l_cust;
    private javax.swing.JMenuItem l_user;
    private javax.swing.JMenu lap;
    private javax.swing.JMenuItem m_customer;
    private javax.swing.JMenuItem m_product;
    private javax.swing.JMenuItem m_user;
    private javax.swing.JMenu master;
    private javax.swing.JMenu ttrs;
    private javax.swing.JMenuItem ttrs_penjualan;
    // End of variables declaration//GEN-END:variables
}
